export const metadata = { title: "Terms of Service — Void Studios" };

export default function TermsPage() {
  return (
    <>
      <h1 className="font-display text-3xl font-bold">Terms of Service</h1>
      <p className="text-sm text-muted-foreground">Last updated: {new Date().getFullYear()}</p>

      <p>
        By accessing or using Void Studios, you agree to these Terms of Service. If you do not
        agree, do not use the service.
      </p>

      <h2>Use of the service</h2>
      <ul>
        <li>You must be at least 18 years old and able to form a binding contract.</li>
        <li>You are responsible for the content you submit and generate.</li>
        <li>You must not use the service for unlawful, infringing or abusive purposes.</li>
      </ul>

      <h2>Accounts</h2>
      <p>
        You are responsible for maintaining the confidentiality of your account credentials and
        for all activity under your account.
      </p>

      <h2>Subscriptions & billing</h2>
      <p>
        Paid plans are billed monthly via Razorpay. Prices are listed in INR and are subject to
        applicable taxes. You may cancel at any time; see our
        <a href="/legal/refund" className="text-primary hover:underline"> Refund Policy</a>.
      </p>

      <h2>AI-generated content</h2>
      <p>
        Content is generated by AI based on your inputs and may require review. You are responsible
        for verifying accuracy and suitability before publishing.
      </p>

      <h2>Limitation of liability</h2>
      <p>
        The service is provided &quot;as is&quot; without warranties of any kind. To the maximum extent
        permitted by law, Void Studios shall not be liable for any indirect or consequential damages.
      </p>

      <h2>Changes</h2>
      <p>We may update these terms; continued use constitutes acceptance of the updated terms.</p>
    </>
  );
}
